apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: podlist2
  name: podlist2
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: podlist
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: podlist
    spec:
      serviceAccountName: rjohnson
      containers:
      - image: saparchitect/podlist:v0.1.0
        name: podlist
        resources:
          requests:
            memory: "16Mi"
            cpu: "300m"
          limits:
            memory: "32Mi"
            cpu: "500m"
        volumeMounts:
        - name: varlog
          mountPath: /var/log
      volumes:
      - name: varlog
        hostPath:
          path: /var/log